# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Test All Xiao Controllers'
on: workflow_dispatch
jobs:
  build:
    if: github.repository_owner == 'manna-harbour'
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '[
        "seeeduino_xiao",
        "seeeduino_xiao_ble"
      ]'
      shield: '["hummingbird"]'
